### ISSUE TITLE
CUDA graphics card is not detected (v4.5.0)

### ISSUE THREAD

**Issue by mkiol** [mkiol/dsnote#111]
Relevant logs:

```
[D] 18:45:31.582684769.582 0x72ab2e18cd00 () - trying features availability update: false
/app/extensions/nvidia/lib/python3.11/site-packages/torch/cuda/__init__.py:141: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0

[D] 18:45:34.436945512.436 0x72ab2e18cd00 add_cuda_dev_devices:407 - scanning for cuda devices
[W] 18:45:34.438195691.438 0x72ab2e18cd00 operator():417 - cuInit error: CUDA_ERROR_UNKNOWN (999)
[W] 18:45:34.438210449.438 0x72ab2e18cd00 add_cuda_devices:510 - cuda init error
[D] 18:45:34.438215409.438 0x72ab2e18cd00 add_cuda_runtime_devices:368 - scanning for cuda runtime devices
[D] 18:45:34.438245766.438 0x72ab2e18cd00 add_cuda_runtime_devices:377 - cuda version: driver=12040, runtime=12040
[W] 18:45:34.438251297.438 0x72ab2e18cd00 add_cuda_runtime_devices:380 - cudaInitDevice error: 999
[W] 18:45:34.438255114.438 0x72ab2e18cd00 add_cuda_runtime_devices:386 - cudaGetDeviceCount error: 999
[W] 18:45:34.438402122.438 0x72ab2e18cd00 add_cuda_devices:515 - cuda runtime get device count error
```

Cause:

- no `/dev/nvidia-uvm` file

Workaround:

- run `nvidia-modprobe -c 0 -u` before starting Speech Note

**Comment by h9j6k** [comment]
Hello,

It seems `nvidia-modprobe -c 0 -u` workaround does not work if the computer resumes from sleep.

On v4.5.0, if computer is put to sleep then resumes from suspension, the `please run nvidia-modprobe -c 0 -u` warning keeps showing on the top and CUDA acceleration is not available. 

If this happens, must reboot to use CUDA again :(

**Comment by jameshibbard** [comment]
Same problem here since updating to v4.5.0

```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=dsnote --file-forwarding net.mkiol.SpeechNote

Gtk-Message: 21:12:01.618: Failed to load module "xapp-gtk3-module"
Qt: Session management error: Could not open network socket
/app/extensions/nvidia/lib/python3.11/site-packages/torch/cuda/__init__.py:141: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
return torch._C._cuda_getDeviceCount() > 0
```

This results in a Warning being displayed in the GUI:

```
Most likely, NVIDIA kernel module has not been fully initialized. Try executing "nvidia-modprobe -c 0 -u" before running Speech Note
```

Running the command before starting Speech Note has no effect.

![Screenshot from 2024-05-29 21-15-29](https://github.com/mkiol/dsnote/assets/1940994/77337369-9937-433a-8788-1184c6fa00f4)

**Comment by mkiol** [comment]
Many thanks for reporting. 

This problem started to occur after upgrading Flatpak runtime to 5.15-23.08 version. I still have not found out what the cause is. I'm testing Speech Note on two systems: Arch and Ubuntu 24.04 (both with NV cards) and I'm observing this issue only on Arch.

@h9j6k @jameshibbard On what system do you run the app? Could you please start with `--verbose` option to see more logs? Thanks!

```
flatpak run net.mkiol.SpeechNote --verbose
```

**Comment by jameshibbard** [comment]
Hi,

Rebooting the PC after upgrading Speech Note seems to have solved the problem for me. After a reboot, I now no longer get the warning and performance has improved considerably.

I'm running Linux Mint 21.3 Cinnamon. Would you still like me to post the output of running with `--verbose`?

**Comment by mkiol** [comment]
@jameshibbard I'm super glad the problem is gone :) If there is no issue additional logs will not be needed.

**Comment by h9j6k** [comment]
Could the issue be related to power saving? Just saw this from the latest nvidia driver release note,

```
**Unified Memory Support**
CUDA and unified memory is not supported when used with Linux power management states S3/S4.
```
https://docs.nvidia.com/datacenter/tesla/tesla-release-notes-535-183-01/index.html

**Comment by hista** [comment]
Hi, I am facing the same issue:

> /app/extensions/nvidia/lib/python3.11/site-packages/torch/cuda/__init__.py:141: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
>   return torch._C._cuda_getDeviceCount() > 0

Running `nvidia-modprobe -c 0 -u` didn't solve anything.

Here is a verbose log:

> flatpak run net.mkiol.SpeechNote --verbose
> [I] 21:45:54.426282295.426 0x7f7a54920d00 init:49 - logging to stderr enabled
> [D] 21:45:54.426394041.426 0x7f7a54920d00 () - version: 4.5.0
> [D] 21:45:54.427027781.427 0x7f7a54920d00 parse_cpuinfo:117 - cpu flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm debug_swap
> [D] 21:45:54.427600200.427 0x7f7a54920d00 parse_cpuinfo:125 - cpuinfo: processor-count=16, flags=[avx, avx2, fma, f16c, ]
> [D] 21:45:54.427820619.427 0x7f7a54920d00 () - translation: "fr_FR"
> [D] 21:45:54.427846391.427 0x7f7a54920d00 () - starting standalone app
> [D] 21:45:54.429309565.429 0x7f7a54920d00 () - app: net.mkiol dsnote
> [D] 21:45:54.429329680.429 0x7f7a54920d00 () - config location: "/home/rm/.var/app/net.mkiol.SpeechNote/config"
> [D] 21:45:54.429340645.429 0x7f7a54920d00 () - data location: "/home/rm/.var/app/net.mkiol.SpeechNote/data/net.mkiol/dsnote"
> [D] 21:45:54.429350003.429 0x7f7a54920d00 () - cache location: "/home/rm/.var/app/net.mkiol.SpeechNote/cache/net.mkiol/dsnote"
> [D] 21:45:54.429361388.429 0x7f7a54920d00 () - settings file: "/home/rm/.var/app/net.mkiol.SpeechNote/config/net.mkiol/dsnote/settings.conf"
> [D] 21:45:54.429369978.429 0x7f7a54920d00 () - platform: "xcb"
> [D] 21:45:54.429388765.429 0x7f7a54920d00 () - nvidia addon exists
> [D] 21:45:54.429418378.429 0x7f7a54920d00 () - enforcing num threads: 0
> [D] 21:45:54.467185329.467 0x7f7a54920d00 () - starting service: app-standalone
> [D] 21:45:54.470350955.470 0x7f7a54920d00 () - mbrola dir: "/app/bin"
> [D] 21:45:54.470392510.470 0x7f7a54920d00 () - espeak dir: "/app/bin"
> [D] 21:45:54.470607133.470 0x7f7a4a000680 loop:88 - py executor loop started
> [D] 21:45:54.470654834.470 0x7f7a4a000680 set_env:84 - set env: PYTHONIOENCODING = utf-8
> [D] 21:45:54.470671526.470 0x7f7a4a000680 set_env:84 - set env: HF_HUB_DISABLE_TELEMETRY = 1
> [D] 21:45:54.470681164.470 0x7f7a4a000680 set_env:84 - set env: HF_HUB_OFFLINE = 1
> [D] 21:45:54.470692967.470 0x7f7a4a000680 set_env:84 - set env: HF_HUB_LOCAL_DIR_AUTO_SYMLINK_THRESHOLD = 100000000000
> [D] 21:45:54.470754009.470 0x7f7a4a000680 set_env:84 - set env: HF_HUB_CACHE = /home/rm/.var/app/net.mkiol.SpeechNote/cache/net.mkiol/dsnote
> [D] 21:45:54.475602320.475 0x7f7a54920d00 () - module already unpacked: "rhvoicedata"
> [D] 21:45:54.475661895.475 0x7f7a54920d00 () - module already unpacked: "rhvoiceconfig"
> [D] 21:45:54.481438188.481 0x7f7a54920d00 () - module already unpacked: "espeakdata"
> [D] 21:45:54.481947051.481 0x7f7a54920d00 () - default stt model not found: "fr_whisper_large"
> [D] 21:45:54.481965490.481 0x7f7a54920d00 () - default tts model not found: "en"
> [D] 21:45:54.481974709.481 0x7f7a54920d00 () - default mnt lang not found: "en"
> [D] 21:45:54.481982740.481 0x7f7a54920d00 () - new default mnt lang: "en"
> [D] 21:45:54.481994124.481 0x7f7a54920d00 () - service refresh status, new state: busy
> [D] 21:45:54.482003763.482 0x7f7a54920d00 () - service state changed: unknown => busy
> [D] 21:45:54.482012772.482 0x7f7a54920d00 () - delaying features availability
> [D] 21:45:54.484953509.484 0x7f7a54920d00 () - runtime prefix: "/app"
> [D] 21:45:54.485432271.485 0x7f7a54920d00 () - available styles: ("Default", "Fusion", "Imagine", "Material", "org.kde.breeze", "org.kde.desktop", "Plasma", "Universal")
> [D] 21:45:54.485432271.485 0x7f7a4aa00680 () - config version: 81 81
> [D] 21:45:54.485614417.485 0x7f7a54920d00 () - style paths: ("/usr/lib/qml/QtQuick/Controls.2")
> [D] 21:45:54.485636417.485 0x7f7a54920d00 () - import paths: ("/usr/lib/qml", "/app/bin", "qrc:/qt-project.org/imports")
> [D] 21:45:54.485646334.485 0x7f7a54920d00 () - library paths: ("/usr/share/runtime/lib/plugins", "/usr/lib/plugins", "/app/bin")
> [D] 21:45:54.485655553.485 0x7f7a54920d00 () - using auto qt style
> [D] 21:45:54.485665052.485 0x7f7a54920d00 () - XDG_CURRENT_DESKTOP: LXQt
> [D] 21:45:54.485674969.485 0x7f7a54920d00 () - switching to style: "org.kde.breeze"
> [D] 21:45:54.486005179.486 0x7f7a54920d00 () - desktop file: "net.mkiol.SpeechNote"
> [D] 21:45:54.488390259.488 0x7f7a4a000680 libs_availability:62 - checking: torch cuda
> [D] 21:45:54.535298455.535 0x7f7a4aa00680 () - models changed
> [D] 21:45:55.773838130.773 0x7f7a54920d00 state_pa_callback:30 - pa authorizing
> [D] 21:45:55.774146758.774 0x7f7a54920d00 state_pa_callback:33 - pa setting name
> [D] 21:45:55.778651381.778 0x7f7a54920d00 state_pa_callback:36 - pa ready
> [D] 21:45:55.779406784.779 0x7f793b400680 source_info_pa_callback:200 - pa source: alsa_output.pci-0000_06_00.6.analog-stereo.monitor Monitor of Family 17h/19h HD Audio Controller Stéréo analogique
> [D] 21:45:55.779485635.779 0x7f793b400680 source_info_pa_callback:200 - pa source: alsa_input.pci-0000_06_00.6.analog-stereo Family 17h/19h HD Audio Controller Stéréo analogique
> [D] 21:45:55.779545280.779 0x7f793b400680 source_info_pa_callback:200 - pa source: alsa_input.usb-LGE_AN-VC300-00.analog-stereo AN-VC300 Stéréo analogique
> [D] 21:45:55.805910921.805 0x7f7a54920d00 () - starting app: app-standalone
> [D] 21:45:55.806739308.806 0x7f7a54920d00 () - app service state: unknown => busy
> [D] 21:45:55.806761658.806 0x7f7a54920d00 () - app busy: false => true
> [D] 21:45:55.806774159.806 0x7f7a54920d00 () - app connected: false  = >  true
> [W] 21:45:55.867300916.867 0x7f7a54920d00 ():36 - file:///usr/lib/qml/QtQuick/Controls.2/org.kde.breeze/ScrollView.qml:36:25: QML ScrollBar: Binding loop detected for property "x"
> [W] 21:45:55.889205655.889 0x7f7a54920d00 ():36 - file:///usr/lib/qml/QtQuick/Controls.2/org.kde.breeze/ScrollView.qml:36:25: QML ScrollBar: Binding loop detected for property "x"
> [W] 21:45:55.906185537.906 0x7f7a54920d00 ():36 - file:///usr/lib/qml/QtQuick/Controls.2/org.kde.breeze/ScrollView.qml:36:25: QML ScrollBar: Binding loop detected for property "x"
> logger error: invalid format string
> qrc:/qml/main.qml:372:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
> logger error: invalid format string
> qrc:/qml/main.qml:363:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
> [W] 21:45:55.946448545.946 0x7f7a54920d00 virtual QVariant ModelSource::item(int) const:81 - ModelSource: Invalid role  -1 "color"
> [W] 21:45:55.946582431.946 0x7f7a54920d00 virtual QVariant ModelSource::item(int) const:81 - ModelSource: Invalid role  -1 "color"
> [W] 21:45:55.961007798.961 0x7f7a54920d00 ():154 - qrc:/qml/ScrollTextArea.qml:154:17: QML MenuItem: Binding loop detected for property "__reserveSpaceForIcon"
> [W] 21:45:55.961053614.961 0x7f7a54920d00 ():154 - qrc:/qml/ScrollTextArea.qml:154:17: QML MenuItem: Binding loop detected for property "__reserveSpaceForIcon"
> logger error: invalid format string
> qrc:/qml/Notepad.qml:24:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
> [W] 21:45:55.984905109.984 0x7f7a54920d00 ():154 - qrc:/qml/ScrollTextArea.qml:154:17: QML MenuItem: Binding loop detected for property "__reserveSpaceForIcon"
> [W] 21:45:55.984944709.984 0x7f7a54920d00 ():154 - qrc:/qml/ScrollTextArea.qml:154:17: QML MenuItem: Binding loop detected for property "__reserveSpaceForIcon"
> [W] 21:45:56.006349524.6 0x7f7a54920d00 ():154 - qrc:/qml/ScrollTextArea.qml:154:17: QML MenuItem: Binding loop detected for property "__reserveSpaceForIcon"
> [W] 21:45:56.006395829.6 0x7f7a54920d00 ():154 - qrc:/qml/ScrollTextArea.qml:154:17: QML MenuItem: Binding loop detected for property "__reserveSpaceForIcon"
> logger error: invalid format string
> qrc:/qml/Translator.qml:30:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
> [W] 21:45:56.049606419.49 0x7f7a54920d00 ():116 - qrc:/qml/MainToolBar.qml:116:29: QML MenuItem: Binding loop detected for property "__reserveSpaceForIcon"
> [W] 21:45:56.049654190.49 0x7f7a54920d00 ():116 - qrc:/qml/MainToolBar.qml:116:29: QML MenuItem: Binding loop detected for property "__reserveSpaceForIcon"
> [W] 21:45:56.052540241.52 0x7f7a54920d00 ():58 - qrc:/qml/MainToolBar.qml:58:29: QML MenuItem: Binding loop detected for property "__reserveSpaceForIcon"
> [W] 21:45:56.052570762.52 0x7f7a54920d00 ():58 - qrc:/qml/MainToolBar.qml:58:29: QML MenuItem: Binding loop detected for property "__reserveSpaceForIcon"
> [D] 21:45:56.065493284.65 0x7f7a54920d00 onCompleted:168 - default font pixel size: 18
> [D] 21:45:56.074143057.74 0x7f7a54920d00 () - default tts model not found: "en"
> [D] 21:45:56.074182587.74 0x7f7a54920d00 () - default mnt lang not found: "en"
> [D] 21:45:56.074191107.74 0x7f7a54920d00 () - new default mnt lang: "en"
> [D] 21:45:56.074204587.74 0x7f7a54920d00 () - service refresh status, new state: busy
> [D] 21:45:56.074219253.74 0x7f7a54920d00 () - service refresh status, new state: busy
> [D] 21:45:56.558526686.558 0x7f7a54920d00 () - trying features availability update: false
> /app/extensions/nvidia/lib/python3.11/site-packages/torch/cuda/__init__.py:141: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
>   return torch._C._cuda_getDeviceCount() > 0
> [D] 21:45:56.747167352.747 0x7f7a4a000680 libs_availability:70 - checking: coqui tts
> [D] 21:45:56.747771409.747 0x7f7a4a000680 libs_availability:78 - checking: whisperspeech tts
> [D] 21:45:56.748097568.748 0x7f7a4a000680 libs_availability:86 - checking: faster-whisper
> [W] 21:45:56.864672439.864 0x7f7a54920d00 ():228 - qrc:/qml/Translator.qml:228:9: QML ColumnLayout (parent or ancestor of QQuickLayoutAttached): Binding loop detected for property "preferredWidth"
> [D] 21:45:56.865761824.865 0x7f7a54920d00 () - stt models changed
> [D] 21:45:56.907306350.907 0x7f7a54920d00 () - update listen
> [D] 21:45:56.907336870.907 0x7f7a54920d00 () - app stt configured: false => true
> [D] 21:45:56.910026528.910 0x7f7a54920d00 () - app active stt model: "" => "fr_whisper_large"
> [D] 21:45:56.940791192.940 0x7f7a54920d00 () - update listen
> [D] 21:45:56.940826322.940 0x7f7a54920d00 () - tts models changed
> [D] 21:45:56.941202836.941 0x7f7a54920d00 () - update listen
> [W] 21:45:56.941272538.941 0x7f7a54920d00 () - no available tts models for in mnt
> [W] 21:45:56.941284271.941 0x7f7a54920d00 () - no available tts models for out mnt
> [D] 21:45:56.941302570.941 0x7f7a54920d00 () - ttt models changed
> [D] 21:45:56.941318563.941 0x7f7a54920d00 () - app ttt punctuation configured: false => true
> [D] 21:45:56.947271415.947 0x7f7a54920d00 () - mnt langs changed
> [D] 21:45:56.947331898.947 0x7f7a54920d00 () - update listen
> [W] 21:45:56.947344399.947 0x7f7a54920d00 () - no available mnt langs
> [W] 21:45:56.947351663.947 0x7f7a54920d00 () - no available mnt out langs
> [D] 21:45:57.399495441.399 0x7f7a4a000680 libs_availability:94 - checking: transformers
> [D] 21:45:57.399532107.399 0x7f7a4a000680 libs_availability:96 - checking: accelerate
> [D] 21:45:57.465977005.465 0x7f7a54920d00 () - trying features availability update: false
> [D] 21:45:58.465953608.465 0x7f7a54920d00 () - trying features availability update: false
> [D] 21:45:58.747007345.747 0x7f7a4a000680 libs_availability:104 - checking: unikud
> [D] 21:45:58.747573269.747 0x7f7a4a000680 libs_availability:115 - checking: mimic3 tts
> [D] 21:45:59.465863652.465 0x7f7a54920d00 () - trying features availability update: false
> [D] 21:45:59.695250208.695 0x7f7a4a000680 libs_availability:123 - checking: gruut
> [D] 21:45:59.695291764.695 0x7f7a4a000680 libs_availability:127 - checking: gruut-de
> [D] 21:45:59.695678195.695 0x7f7a4a000680 libs_availability:135 - checking: gruut-es
> [D] 21:45:59.696052195.696 0x7f7a4a000680 libs_availability:143 - checking: gruut-fr
> [D] 21:45:59.696540945.696 0x7f7a4a000680 libs_availability:151 - checking: gruut-it
> [D] 21:45:59.696969840.696 0x7f7a4a000680 libs_availability:159 - checking: gruut-ru
> [D] 21:45:59.697369402.697 0x7f7a4a000680 libs_availability:167 - checking: gruut-fa
> [D] 21:45:59.697805351.697 0x7f7a4a000680 libs_availability:175 - checking: gruut-sw
> [D] 21:45:59.698166640.698 0x7f7a4a000680 libs_availability:183 - checking: gruut-nl
> [D] 21:45:59.698689193.698 0x7f7a4a000680 libs_availability:194 - checking: mecab
> [D] 21:45:59.702043809.702 0x7f7a4a000680 libs_availability:196 - checking: unidic-lite
> [D] 21:45:59.702903695.702 0x7f7a4a000680 libs_availability:203 - py libs availability: [coqui-tts=true, faster-whisper=true, mimic3-tts=true, whisperspeech-tts=true, transformers=true, unikud=true, gruut_de=true, gruut_es=true, gruut_fa=true, gruut_fr=true, gruut_nl=true, gruut_it=true, gruut_ru=true, gruut_sw=true, mecab=true, torch-cuda=false]
> [D] 21:46:00.466343042.466 0x7f7a54920d00 () - trying features availability update: true
> [D] 21:46:00.466396541.466 0x7f7a54920d00 () - features availability ready
> [W] 21:46:00.508077606.508 0x7f7a54920d00 has_hip:80 - failed to open whisper-hipblas lib: libwhisper-hipblas.so: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type
> [D] 21:46:00.539628614.539 0x7f7a54920d00 () - updating models using availability: tts_coqui, tts_mimic3, tts_mimic3_de, tts_mimic3_es, tts_mimic3_fr, tts_mimic3_it, tts_mimic3_ru, tts_mimic3_sw, tts_mimic3_fa, tts_mimic3_nl, tts_rhvoice, tts_whisperspeech, stt_fasterwhisper, stt_ds, stt_vosk, mnt_bergamot, ttt_hftc option_r,
> [D] 21:46:00.539948207.539 0x7f7a54920d00 () - updating model using availability internal
> [D] 21:46:00.542360874.542 0x7f7a54920d00 () - default tts model not found: "en"
> [D] 21:46:00.542590303.542 0x7f7a54920d00 () - default mnt lang not found: "en"
> [D] 21:46:00.542787116.542 0x7f7a54920d00 () - new default mnt lang: "en"
> [D] 21:46:00.543046157.543 0x7f7a54920d00 () - service refresh status, new state: idle
> [D] 21:46:00.543252259.543 0x7f7a54920d00 () - service state changed: busy => idle
> [D] 21:46:00.543477916.543 0x7f7a54920d00 () - scan cuda: true
> [D] 21:46:00.543672144.543 0x7f7a54920d00 () - scan hip: true
> [D] 21:46:00.543860716.543 0x7f7a54920d00 () - scan opencl: true
> [D] 21:46:00.544056621.544 0x7f7a54920d00 () - scan opencl legacy: false
> [D] 21:46:00.544250570.544 0x7f7a54920d00 () - gpu feature flags: stt-whispercpp-cuda, stt-whispercpp-opencl, stt-fasterwhisper-cuda,
> [D] 21:46:00.544446125.544 0x7f7a54920d00 add_hip_devices:523 - scanning for hip devices
> [W] 21:46:00.544801967.544 0x7f7a54920d00 hip_api:314 - failed to open hip lib: libamdhip64.so: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type
> [D] 21:46:00.545060100.545 0x7f7a54920d00 add_cuda_devices:500 - scanning for cuda devices
> [D] 21:46:00.545258729.545 0x7f7a54920d00 add_cuda_dev_devices:403 - scanning for cuda devices
> [W] 21:46:00.603897955.603 0x7f7a54920d00 operator():413 - cuInit error: CUDA_ERROR_UNKNOWN (999)
> [W] 21:46:00.603946006.603 0x7f7a54920d00 add_cuda_devices:507 - cuda init error
> [D] 21:46:00.603959555.603 0x7f7a54920d00 add_cuda_runtime_devices:366 - scanning for cuda runtime devices
> [D] 21:46:00.604048882.604 0x7f7a54920d00 add_cuda_runtime_devices:375 - cuda version: driver=12050, runtime=12040
> [W] 21:46:00.604058450.604 0x7f7a54920d00 add_cuda_runtime_devices:380 - cudaGetDeviceCount error: 999
> [D] 21:46:00.604227955.604 0x7f7a54920d00 add_opencl_devices:563 - scanning for opencl devices
> [D] 21:46:00.665345430.665 0x7f7a54920d00 add_opencl_devices:580 - opencl number of platforms: 1
> [D] 21:46:00.665378814.665 0x7f7a54920d00 add_opencl_devices:605 - opencl platform: 0, name=Clover, vendor=Mesa
> [D] 21:46:00.665393480.665 0x7f7a54920d00 add_opencl_devices:619 - opencl number of devices: 0
> [W] 21:46:00.665564312.665 0x7f7a54920d00 () - *********************************************
> [W] 21:46:00.665576465.665 0x7f7a54920d00 () - Most likely, NVIDIA kernel module has not been fully initialized. Try executing 'nvidia-modprobe -c 0 -u' before running Speech Note
> [W] 21:46:00.665584077.665 0x7f7a54920d00 () - *********************************************
> [D] 21:46:00.665815531.665 0x7f7a54920d00 () - service refresh status, new state: idle
> [D] 21:46:00.666835284.666 0x7f7a54920d00 () - app service state: busy => idle
> [W] 21:46:00.674023069.674 0x7f7a54920d00 () - no available mnt langs
> [W] 21:46:00.674041297.674 0x7f7a54920d00 () - no available mnt out langs
> [W] 21:46:00.674050796.674 0x7f7a54920d00 () - no available tts models for in mnt
> [W] 21:46:00.674058339.674 0x7f7a54920d00 () - no available tts models for out mnt
> [W] 21:46:00.674065462.674 0x7f7a54920d00 () - invalid task, reseting task state
> [D] 21:46:00.674492542.674 0x7f7a54920d00 () - app busy: true => false
> [D] 21:46:00.675313736.675 0x7f7a54920d00 () - stt models changed
> [D] 21:46:00.675525494.675 0x7f7a54920d00 () - update listen
> [D] 21:46:00.675601202.675 0x7f7a54920d00 () - tts models changed
> [D] 21:46:00.675845507.675 0x7f7a54920d00 () - update listen
> [W] 21:46:00.676103640.676 0x7f7a54920d00 () - no available tts models for in mnt
> [W] 21:46:00.676122917.676 0x7f7a54920d00 () - no available tts models for out mnt
> [D] 21:46:00.676136955.676 0x7f7a54920d00 () - ttt models changed
> [D] 21:46:00.682460803.682 0x7f7a54920d00 () - mnt langs changed
> [D] 21:46:00.682502987.682 0x7f7a54920d00 () - update listen
> [W] 21:46:00.682527851.682 0x7f7a54920d00 () - no available mnt langs
> [W] 21:46:00.682536371.682 0x7f7a54920d00 () - no available mnt out langs

Could you please help me to fix it?

**Comment by mkiol** [comment]
@hista 

Can you check if you have the `/dev/nvidia-uvm` device file in your system? It is used by CUDA to communicate with the kernel driver. This "CUDA_ERROR_UNKNOWN (999)" problem occurs because `/dev/nvidia-uvm` is missing. Normally, CUDA runtime calls `nvidia-modprobe` to create that device file automatically.  For unknown to me reason, this doesn't work always with Flatpak apps, but you should also be able to create this device file by calling `nvidia-modprobe -c 0 -u` manually. 

Here is more details about it and different method how to handle this problem: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#runfile-verifications

From my system where nvidia cuda driver has been initialized properly:

```
$ ls /dev | grep nvidia
nvidia0
nvidiactl
nvidia-modeset
nvidia-uvm
nvidia-uvm-tools
```

**Comment by Getarhubar** [comment]
If it helps, with Linux Mint it was quite a process to find the graphics card to get Speech Note to work but when switching to Ubuntu because of issues with Linux Mint, Ubuntu 24.04 got the correct graphics card automatically without needing to do anything. I don't know if this is new to the latest 24.04 as I am new to Linux but with Ubuntu it was effortless compared with Mint

**Comment by mkiol** [comment]
@Getarhubar Thanks for the info. I'm glad the problem doesn't occur on Ubuntu.

**Comment by Getarhubar** [comment]
With Ubuntu I'm not having any of the problems I had with Mint. I just wish Ubuntu had a user friendly interface like Mint :)

**Comment by nerumo** [comment]
I'm having this issue with:
- Kubuntu 24.04-24.10 (testing)
- Nvidia 550 and Nvidia 560
- installed as flatpak

After rebooting it works again

**Comment by nerumo** [comment]
Here are my logs with the verbose flag:

[speechnote.txt](https://github.com/user-attachments/files/17074449/speechnote.txt)

`cuInit error: CUDA_ERROR_UNKNOWN (999)`

**Comment by GjnYGDZPODZg** [comment]
> If this happens, must reboot to use CUDA again :(

No need to reboot: I just quit Speech Note before I suspend and reopen it when I come back.

Update: It only seems to work a few times. Then the notice appears again...

**Comment by jmlucjav** [comment]
hi,

same issue in 4.6.1 in ubuntu24.04. After returning from sleep it happens:

```~$ flatpak run net.mkiol.SpeechNote --verbose
Gtk-Message: 17:08:36.478: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:08:36.478: Failed to load module "canberra-gtk-module"
qt.qpa.qgnomeplatform: Could not find color scheme  ""
Qt: Session management error: Could not open network socket
[I] 16:08:36.489574506.489 0x7ab577d86d00 init:49 - logging to stderr enabled
[D] 16:08:36.489600575.489 0x7ab577d86d00 () - version: 4.6.1
[D] 16:08:36.489844981.489 0x7ab577d86d00 parse_cpuinfo:121 - cpu flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good amd_lbr_v2 nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba perfmon_v2 ibrs ibpb stibp ibrs_enhanced vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local user_shstk avx512_bf16 clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif x2avic v_spec_ctrl vnmi avx512vbmi umip pku ospkeavx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid overflow_recov succor smca fsrm flush_l1d
[D] 16:08:36.490175218.490 0x7ab577d86d00 parse_cpuinfo:129 - cpuinfo: processor-count=24, flags=[avx, avx2, avx512, fma, f16c, sse4.1, bmi2, ]
[D] 16:08:36.490203942.490 0x7ab577d86d00 () - translation: "en_US"
[D] 16:08:36.490209913.490 0x7ab577d86d00 () - starting standalone app
[D] 16:08:36.490582630.490 0x7ab577d86d00 () - app: net.mkiol dsnote
[D] 16:08:36.490588962.490 0x7ab577d86d00 () - config location: "/home/jm/.var/app/net.mkiol.SpeechNote/config"
[D] 16:08:36.490592699.490 0x7ab577d86d00 () - data location: "/home/jm/.var/app/net.mkiol.SpeechNote/data/net.mkiol/dsnote"
[D] 16:08:36.490596005.490 0x7ab577d86d00 () - cache location: "/home/jm/.var/app/net.mkiol.SpeechNote/cache/net.mkiol/dsnote"
[D] 16:08:36.490598369.490 0x7ab577d86d00 () - settings file: "/home/jm/.var/app/net.mkiol.SpeechNote/config/net.mkiol/dsnote/settings.conf"
[D] 16:08:36.490600533.490 0x7ab577d86d00 () - platform: "xcb"
[D] 16:08:36.490605212.490 0x7ab577d86d00 () - nvidia addon exists
[D] 16:08:36.490616633.490 0x7ab577d86d00 () - nvidia gpu detected
[D] 16:08:36.490620591.490 0x7ab577d86d00 () - amd gpu detected
[D] 16:08:36.490642962.490 0x7ab577d86d00 () - enforcing num threads: 1
[D] 16:08:36.502472217.502 0x7ab577d86d00 () - starting service: app-standalone
[D] 16:08:36.503667080.503 0x7ab577d86d00 () - mbrola dir: "/app/bin"
[D] 16:08:36.503682088.503 0x7ab577d86d00 () - espeak dir: "/app/bin"
[D] 16:08:36.503741438.503 0x7ab56b400680 loop:88 - py executor loop started
[D] 16:08:36.503751026.503 0x7ab56b400680 set_env:84 - set env: PYTHONIOENCODING = utf-8
[D] 16:08:36.503754503.503 0x7ab56b400680 set_env:84 - set env: HF_HUB_DISABLE_TELEMETRY = 1
[D] 16:08:36.503757178.503 0x7ab56b400680 set_env:84 - set env: HF_HUB_OFFLINE = 1
[D] 16:08:36.503759843.503 0x7ab56b400680 set_env:84 - set env: HF_HUB_LOCAL_DIR_AUTO_SYMLINK_THRESHOLD = 100000000000
[D] 16:08:36.503777696.503 0x7ab56b400680 set_env:84 - set env: HF_HUB_CACHE = /home/jm/.var/app/net.mkiol.SpeechNote/cache/net.mkiol/dsnote
[D] 16:08:36.505872841.505 0x7ab577d86d00 () - module already unpacked: "rhvoicedata"
[D] 16:08:36.505890995.505 0x7ab577d86d00 () - module already unpacked: "rhvoiceconfig"
[D] 16:08:36.508156959.508 0x7ab577d86d00 () - module already unpacked: "espeakdata"
[D] 16:08:36.508278797.508 0x7ab577d86d00 () - default stt model not found: "en_whisper_distil_large3"
[D] 16:08:36.508283135.508 0x7ab577d86d00 () - default tts model not found: "en"
[D] 16:08:36.508286642.508 0x7ab577d86d00 () - default mnt lang not found: "en"
[D] 16:08:36.508289357.508 0x7ab577d86d00 () - new default mnt lang: "en"
[D] 16:08:36.508293054.508 0x7ab577d86d00 () - service refresh status, new state: busy
[D] 16:08:36.508295629.508 0x7ab577d86d00 () - service state changed: unknown => busy
[D] 16:08:36.508298804.508 0x7ab577d86d00 () - delaying features availability
[D] 16:08:36.509231567.509 0x7ab577d86d00 () - runtime prefix: "/app"
[D] 16:08:36.509297090.509 0x7ab56b400680 libs_availability:63 - checking: torch cuda
[D] 16:08:36.509353535.509 0x7ab577d86d00 () - available styles: ("Default", "Fusion", "Imagine", "Material", "org.kde.breeze", "org.kde.desktop", "Plasma", "Universal")
[D] 16:08:36.509380235.509 0x7ab577d86d00 () - style paths: ("/usr/lib/qml/QtQuick/Controls.2")
[D] 16:08:36.509387138.509 0x7ab577d86d00 () - import paths: ("/usr/lib/qml", "/app/bin", "qrc:/qt-project.org/imports")
[D] 16:08:36.509390484.509 0x7ab577d86d00 () - library paths: ("/usr/share/runtime/lib/plugins", "/usr/lib/plugins", "/app/bin")
[D] 16:08:36.509394011.509 0x7ab577d86d00 () - using auto qt style
[D] 16:08:36.509396716.509 0x7ab577d86d00 () - XDG_CURRENT_DESKTOP: ubuntu:GNOME
[D] 16:08:36.509399732.509 0x7ab577d86d00 () - switching to style: "org.kde.breeze"
[D] 16:08:36.509486253.509 0x7ab577d86d00 () - desktop file: "net.mkiol.SpeechNote"
[D] 16:08:36.509533592.509 0x7ab56be00680 () - config version: 91 91
[D] 16:08:36.525718044.525 0x7ab56be00680 () - models changed
[D] 16:08:37.022942756.22 0x7ab577d86d00 state_pa_callback:30 - pa authorizing
[D] 16:08:37.023134685.23 0x7ab577d86d00 state_pa_callback:33 - pa setting name
[D] 16:08:37.024612937.24 0x7ab577d86d00 state_pa_callback:36 - pa ready
[D] 16:08:37.024893281.24 0x7ab482000680 source_info_pa_callback:206 - pa source: alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1.monitor Monitor of AD102 High Definition Audio Controller Digital Stereo (HDMI 2)
[D] 16:08:37.024929288.24 0x7ab482000680 source_info_pa_callback:206 - pa source: alsa_output.pci-0000_0e_00.1.hdmi-stereo.monitor Monitor of Rembrandt Radeon High Definition Audio Controller Digital Stereo (HDMI)
[D] 16:08:37.024949987.24 0x7ab482000680 source_info_pa_callback:206 - pa source: alsa_output.pci-0000_0e_00.6.analog-stereo.monitor Monitor of Family 17h/19h HD Audio Controller Analog Stereo
[D] 16:08:37.024967579.24 0x7ab482000680 source_info_pa_callback:206 - pa source: alsa_input.pci-0000_0e_00.6.analog-stereo Family 17h/19h HD Audio Controller Analog Stereo
[D] 16:08:37.024986625.24 0x7ab482000680 source_info_pa_callback:206 - pa source: alsa_input.usb-_Webcam_C170-02.mono-fallback Webcam C170 Mono
[D] 16:08:37.033264543.33 0x7ab577d86d00 () - starting app: app-standalone
[D] 16:08:37.033459498.33 0x7ab577d86d00 () - app service state: unknown => busy
[D] 16:08:37.033465168.33 0x7ab577d86d00 () - app busy: false => true
[D] 16:08:37.033469506.33 0x7ab577d86d00 () - app connected: false  = >  true
[W] 16:08:37.052632505.52 0x7ab577d86d00 ():36 - file:///usr/lib/qml/QtQuick/Controls.2/org.kde.breeze/ScrollView.qml:36:25: QML ScrollBar: Binding loop detected for property "x"
[W] 16:08:37.057867858.57 0x7ab577d86d00 ():36 - file:///usr/lib/qml/QtQuick/Controls.2/org.kde.breeze/ScrollView.qml:36:25: QML ScrollBar: Binding loop detected for property "x"
[W] 16:08:37.062407520.62 0x7ab577d86d00 ():36 - file:///usr/lib/qml/QtQuick/Controls.2/org.kde.breeze/ScrollView.qml:36:25: QML ScrollBar: Binding loop detected for property "x"
logger error: invalid format string
qrc:/qml/main.qml:386:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
logger error: invalid format string
qrc:/qml/main.qml:377:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[W] 16:08:37.082662880.82 0x7ab577d86d00 virtual QVariant ModelSource::item(int) const:81 - ModelSource: Invalid role  -1 "color"
[W] 16:08:37.082685963.82 0x7ab577d86d00 virtual QVariant ModelSource::item(int) const:81 - ModelSource: Invalid role  -1 "color"
[W] 16:08:37.086827492.86 0x7ab577d86d00 ():184 - qrc:/qml/ScrollTextArea.qml:184:17: QML MenuItem: Binding loop detected for property "__reserveSpaceForIcon"
[W] 16:08:37.086836829.86 0x7ab577d86d00 ():184 - qrc:/qml/ScrollTextArea.qml:184:17: QML MenuItem: Binding loop detected for property "__reserveSpaceForIcon"
logger error: invalid format string
qrc:/qml/Notepad.qml:24:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[W] 16:08:37.093839495.93 0x7ab577d86d00 ():184 - qrc:/qml/ScrollTextArea.qml:184:17: QML MenuItem: Binding loop detected for property "__reserveSpaceForIcon"
[W] 16:08:37.093848832.93 0x7ab577d86d00 ():184 - qrc:/qml/ScrollTextArea.qml:184:17: QML MenuItem: Binding loop detected for property "__reserveSpaceForIcon"
[W] 16:08:37.100568128.100 0x7ab577d86d00 ():184 - qrc:/qml/ScrollTextArea.qml:184:17: QML MenuItem: Binding loop detected for property "__reserveSpaceForIcon"
[W] 16:08:37.100577926.100 0x7ab577d86d00 ():184 - qrc:/qml/ScrollTextArea.qml:184:17: QML MenuItem: Binding loop detected for property "__reserveSpaceForIcon"
logger error: invalid format string
qrc:/qml/Translator.qml:30:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[W] 16:08:37.121318933.121 0x7ab577d86d00 ():116 - qrc:/qml/MainToolBar.qml:116:29: QML MenuItem: Binding loop detected for property "__reserveSpaceForIcon"
[W] 16:08:37.121336726.121 0x7ab577d86d00 ():116 - qrc:/qml/MainToolBar.qml:116:29: QML MenuItem: Binding loop detected for property "__reserveSpaceForIcon"
[W] 16:08:37.122281492.122 0x7ab577d86d00 ():58 - qrc:/qml/MainToolBar.qml:58:29: QML MenuItem: Binding loop detected for property "__reserveSpaceForIcon"
[W] 16:08:37.122292532.122 0x7ab577d86d00 ():58 - qrc:/qml/MainToolBar.qml:58:29: QML MenuItem: Binding loop detected for property "__reserveSpaceForIcon"
[D] 16:08:37.126033222.126 0x7ab577d86d00 onCompleted:168 - default font pixel size: 14
[D] 16:08:37.129263769.129 0x7ab577d86d00 () - default tts model not found: "en"
[D] 16:08:37.129272956.129 0x7ab577d86d00 () - default mnt lang not found: "en"
[D] 16:08:37.129277064.129 0x7ab577d86d00 () - new default mnt lang: "en"
[D] 16:08:37.129282223.129 0x7ab577d86d00 () - service refresh status, new state: busy
[D] 16:08:37.129288295.129 0x7ab577d86d00 () - service refresh status, new state: busy
/app/extensions/nvidia/lib/python3.11/site-packages/torch/cuda/__init__.py:141: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
[D] 16:08:37.189123434.189 0x7ab56b400680 libs_availability:85 - checking: coqui tts
[D] 16:08:37.189421120.189 0x7ab56b400680 libs_availability:93 - checking: whisperspeech tts
[D] 16:08:37.189528691.189 0x7ab56b400680 libs_availability:101 - checking: faster-whisper
[D] 16:08:37.380714453.380 0x7ab577d86d00 () - stt models changed
[D] 16:08:37.382920165.382 0x7ab577d86d00 () - update listen
[D] 16:08:37.382929533.382 0x7ab577d86d00 () - app stt configured: false => true
[D] 16:08:37.390007288.390 0x7ab577d86d00 () - app active stt model: "" => "en_whisper_distil_large3"
[D] 16:08:37.390158260.390 0x7ab577d86d00 () - update listen
[D] 16:08:37.390163380.390 0x7ab577d86d00 () - tts models changed
[D] 16:08:37.390257786.390 0x7ab577d86d00 () - update listen
[W] 16:08:37.390264489.390 0x7ab577d86d00 () - no available tts models for in mnt
[W] 16:08:37.390266993.390 0x7ab577d86d00 () - no available tts models for out mnt
[D] 16:08:37.390269388.390 0x7ab577d86d00 () - ttt models changed
[D] 16:08:37.391611666.391 0x7ab577d86d00 () - mnt langs changed
[D] 16:08:37.391634068.391 0x7ab577d86d00 () - update listen
[W] 16:08:37.391637585.391 0x7ab577d86d00 () - no available mnt langs
[W] 16:08:37.391639889.391 0x7ab577d86d00 () - no available mnt out langs
[D] 16:08:37.401930558.401 0x7ab56b400680 libs_availability:109 - checking: transformers
[D] 16:08:37.401941479.401 0x7ab56b400680 libs_availability:111 - checking: accelerate
[D] 16:08:37.446616278.446 0x7ab577d86d00 () - trying features availability update: false
[D] 16:08:37.877688787.877 0x7ab56b400680 libs_availability:119 - checking: unikud
[D] 16:08:37.877810384.877 0x7ab56b400680 libs_availability:130 - checking: mimic3 tts
[D] 16:08:38.170232228.170 0x7ab56b400680 libs_availability:138 - checking: gruut
[D] 16:08:38.170253979.170 0x7ab56b400680 libs_availability:142 - checking: gruut-de
[D] 16:08:38.170367631.170 0x7ab56b400680 libs_availability:150 - checking: gruut-es
[D] 16:08:38.170461707.170 0x7ab56b400680 libs_availability:158 - checking: gruut-fr
[D] 16:08:38.170584667.170 0x7ab56b400680 libs_availability:166 - checking: gruut-it
[D] 16:08:38.170672270.170 0x7ab56b400680 libs_availability:174 - checking: gruut-ru
[D] 16:08:38.170759794.170 0x7ab56b400680 libs_availability:182 - checking: gruut-fa
[D] 16:08:38.170869379.170 0x7ab56b400680 libs_availability:190 - checking: gruut-sw
[D] 16:08:38.170952514.170 0x7ab56b400680 libs_availability:198 - checking: gruut-nl
[D] 16:08:38.171050798.171 0x7ab56b400680 libs_availability:209 - checking: mecab
[D] 16:08:38.172237836.172 0x7ab56b400680 libs_availability:211 - checking: unidic-lite
[D] 16:08:38.172433281.172 0x7ab56b400680 libs_availability:218 - py libs availability: [coqui-tts=true, faster-whisper=true, mimic3-tts=true, whisperspeech-tts=true, transformers=true, unikud=true, gruut_de=true, gruut_es=true, gruut_fa=true, gruut_fr=true, gruut_nl=true, gruut_it=true, gruut_ru=true, gruut_sw=true, mecab=true, torch-cuda=false, torch-hip=false]
[D] 16:08:38.447308547.447 0x7ab577d86d00 () - trying features availability update: true
[D] 16:08:38.447321211.447 0x7ab577d86d00 () - features availability ready
[W] 16:08:38.462730344.462 0x7ab577d86d00 has_hip:96 - failed to open whisper-hipblas lib: libwhisper-hipblas.so: cannot open shared object file: No such file or directory
[D] 16:08:38.474854460.474 0x7ab577d86d00 () - updating models using availability: tts_coqui, tts_mimic3, tts_mimic3_de, tts_mimic3_es, tts_mimic3_fr, tts_mimic3_it, tts_mimic3_ru, tts_mimic3_sw, tts_mimic3_fa, tts_mimic3_nl, tts_rhvoice, tts_whisperspeech, stt_fasterwhisper, stt_ds, stt_vosk, mnt_bergamot, ttt_hftc option_r,
[D] 16:08:38.474866462.474 0x7ab577d86d00 () - updating model using availability internal
[D] 16:08:38.475923587.475 0x7ab577d86d00 () - default tts model not found: "en"
[D] 16:08:38.475928547.475 0x7ab577d86d00 () - default mnt lang not found: "en"
[D] 16:08:38.475930741.475 0x7ab577d86d00 () - new default mnt lang: "en"
[D] 16:08:38.475949396.475 0x7ab577d86d00 () - service refresh status, new state: idle
[D] 16:08:38.475952902.475 0x7ab577d86d00 () - service state changed: busy => idle
[D] 16:08:38.475967389.475 0x7ab577d86d00 () - scan cuda: true
[D] 16:08:38.475970044.475 0x7ab577d86d00 () - scan hip: true
[D] 16:08:38.475972609.475 0x7ab577d86d00 () - scan openvino: true
[D] 16:08:38.475975294.475 0x7ab577d86d00 () - scan openvino_gpu: false
[D] 16:08:38.475977919.475 0x7ab577d86d00 () - scan opencl: true
[D] 16:08:38.475980504.475 0x7ab577d86d00 () - scan opencl legacy: false
[D] 16:08:38.475983780.475 0x7ab577d86d00 () - hw feature flags: stt-whispercpp-cuda, stt-whispercpp-openvino, stt-whispercpp-opencl, stt-fasterwhisper-cuda,
[D] 16:08:38.475987016.475 0x7ab577d86d00 add_hip_devices:655 - scanning for hip devices
[W] 16:08:38.476029175.476 0x7ab577d86d00 hip_api:443 - failed to open hip lib: libamdhip64.so: cannot open shared object file: No such file or directory
[D] 16:08:38.476048921.476 0x7ab577d86d00 add_cuda_devices:632 - scanning for cuda devices
[D] 16:08:38.476051136.476 0x7ab577d86d00 add_cuda_dev_devices:534 - scanning for cuda devices
[W] 16:08:38.490894582.490 0x7ab577d86d00 operator():544 - cuInit error: CUDA_ERROR_UNKNOWN (999)
[W] 16:08:38.490907076.490 0x7ab577d86d00 add_cuda_devices:639 - cuda init error
[D] 16:08:38.490912065.490 0x7ab577d86d00 add_cuda_runtime_devices:497 - scanning for cuda runtime devices
[D] 16:08:38.490927704.490 0x7ab577d86d00 add_cuda_runtime_devices:506 - cuda version: driver=12040, runtime=12040
[W] 16:08:38.490930289.490 0x7ab577d86d00 add_cuda_runtime_devices:511 - cudaGetDeviceCount error: 999
[D] 16:08:38.490978749.490 0x7ab577d86d00 add_openvino_devices:813 - scanning for openvino devices
[D] 16:08:38.491229478.491 0x7ab577d86d00 add_openvino_devices:825 - openvino version: build=2024.1.0-15008-f4afc983258-releases/2024/1, description=OpenVINO Runtime
[D] 16:08:38.573695635.573 0x7ab577d86d00 add_openvino_devices:852 - openvino number of devices: 1
[D] 16:08:38.573718188.573 0x7ab577d86d00 add_openvino_devices:858 - openvino device: 0, name=CPU, full-name=AMD Ryzen 9 7900X 12-Core Processor
[D] 16:08:38.573953337.573 0x7ab577d86d00 add_opencl_devices:695 - scanning for opencl devices
[D] 16:08:38.574018889.574 0x7ab577d86d00 add_opencl_devices:712 - opencl number of platforms: 1
[D] 16:08:38.574028497.574 0x7ab577d86d00 add_opencl_devices:737 - opencl platform: 0, name=Clover, vendor=Mesa
[D] 16:08:38.574031112.574 0x7ab577d86d00 add_opencl_devices:751 - opencl number of devices: 1
[D] 16:08:38.574035100.574 0x7ab577d86d00 add_opencl_devices:775 - opencl device: 0, platform name=Clover, device name=AMD Radeon Graphics (radeonsi, raphael_mendocino, LLVM 17.0.6, DRM 3.57, 6.8.0-49-generic), types=[GPU, ]
[W] 16:08:38.574094881.574 0x7ab577d86d00 () - *********************************************
[W] 16:08:38.574100562.574 0x7ab577d86d00 () - Most likely, NVIDIA kernel module has not been fully initialized. Try executing 'nvidia-modprobe -c 0 -u' before running Speech Note
[W] 16:08:38.574104049.574 0x7ab577d86d00 () - *********************************************
[D] 16:08:38.574129827.574 0x7ab577d86d00 () - nvidia gpu detected
[D] 16:08:38.574134445.574 0x7ab577d86d00 () - amd gpu detected
[D] 16:08:38.574137401.574 0x7ab577d86d00 () - hw accel detected
[D] 16:08:38.574281350.574 0x7ab577d86d00 () - service refresh status, new state: idle
[D] 16:08:38.574323940.574 0x7ab577d86d00 () - app service state: busy => idle
[W] 16:08:38.576038694.576 0x7ab577d86d00 () - no available mnt langs
[W] 16:08:38.576045286.576 0x7ab577d86d00 () - no available mnt out langs
[W] 16:08:38.576048422.576 0x7ab577d86d00 () - no available tts models for in mnt
[W] 16:08:38.576050686.576 0x7ab577d86d00 () - no available tts models for out mnt
[W] 16:08:38.576053301.576 0x7ab577d86d00 () - invalid task, reseting task state
[D] 16:08:38.576157085.576 0x7ab577d86d00 () - app busy: true => false
[D] 16:08:38.576402985.576 0x7ab577d86d00 () - stt models changed
[D] 16:08:38.576450303.576 0x7ab577d86d00 () - update listen
[D] 16:08:38.576461524.576 0x7ab577d86d00 () - tts models changed
[D] 16:08:38.576487302.576 0x7ab577d86d00 () - update listen
[W] 16:08:38.576546022.576 0x7ab577d86d00 () - no available tts models for in mnt
[W] 16:08:38.576549298.576 0x7ab577d86d00 () - no available tts models for out mnt
[D] 16:08:38.576551252.576 0x7ab577d86d00 () - ttt models changed
[D] 16:08:38.577650466.577 0x7ab577d86d00 () - mnt langs changed
[D] 16:08:38.577662568.577 0x7ab577d86d00 () - update listen
[W] 16:08:38.577667788.577 0x7ab577d86d00 () - no available mnt langs
[W] 16:08:38.577669782.577 0x7ab577d86d00 () - no available mnt out langs
[W] 16:08:38.578294369.578 0x7ab577d86d00 () - Qt Quick Layouts: Polish loop detected. Aborting after two iterations.
```

**Comment by mkiol** [comment]
I recently released version [4.7.0 Beta](https://github.com/mkiol/dsnote/issues/179). This new version includes support for Vulkan GPU acceleration for WhisperCpp. From my tests, it appears to be just as fast as CUDA. Maybe this problem can be mitigate simply by not using CUDA 🤔

**Comment by jmlucjav** [comment]
Tried 4.7Beta, and it seems to me I am getting the same issue:

![image](https://github.com/user-attachments/assets/cc53a70b-f8df-4fd5-a48d-09d56493a61e)

**Comment by jmlucjav** [comment]
I stand corrected...after unistalling the nvidia addon. I don't get the warming,and indeed perf with whipercpp-distill-large-v3 is excellent in my rtx 4070...

thanks!!!

**Comment by mkiol** [comment]
Cool. I'm glad it helped!

**Comment by mkiol** [comment]
The new version 4.7.0 is out and available on flathub.

The new version includes:

- Support for Vulkan GPU acceleration in _WhisperCpp_. Vulkan acceleration enables much faster STT decoding with Intel, AMD or NVIDIA graphics cards. With Vulkan, decoding is quicker than with OpenVINO, OpenCL and ROCm, but still may be slightly slower compared to CUDA. The biggest advantage of Vulkan is that you can use it without installing any GPU acceleration add-ons.

Vulkan is not a fix, but rather a "workaround".
