### ISSUE TITLE
CUDA not recognized

### ISSUE THREAD

**Issue by Kiskadee-dev** [mkiol/dsnote#42]
I'm not sure why, but does seem to be related to flatpak

On system:
NVIDIA-SMI 535.113.01             Driver Version: 535.113.01   CUDA Version: 12.2
NVIDIA GeForce 940M (2GB VRAM) (Should be enough to run the small whisper)

On flatpak:

> nvidia-535-104-05                     org.freedesktop.Platform.GL.nvidia-535-104-05                         1.4         user
nvidia-535-113-01                     org.freedesktop.Platform.GL.nvidia-535-113-01                         1.4         user
nvidia-535-98                         org.freedesktop.Platform.GL.nvidia-535-98                             1.4         user
nvidia-535-104-05                     org.freedesktop.Platform.GL32.nvidia-535-104-05                       1.4         user
nvidia-535-113-01                     org.freedesktop.Platform.GL32.nvidia-535-113-01                       1.4         user
nvidia-535-98                         org.freedesktop.Platform.GL32.nvidia-535-98                           1.4         user

Logs
> [D] 14:13:45.593 0x7f5d825ff600 process_buff:226 - vad: no speech
[D] 14:13:45.593 0x7f5d825ff600 set_processing_state:430 - processing state: idle => decoding
[D] 14:13:45.593 0x7f5d825ff600 set_speech_detection_status:508 - speech detection status: speech-detected => decoding (no-speech)
[D] 14:13:45.593 0x7f5d825ff600 () - service refresh status, new state: listening-single-sentence
[D] 14:13:45.593 0x7f5d825ff600 () - task state changed: 1 => 2
[D] 14:13:45.593 0x7f5d825ff600 process_buff:284 - speech frame: samples=51360
[D] 14:13:45.593 0x7f5d825ff600 decode_speech:350 - speech decoding started
[D] 14:13:45.597 0x7f5de77bbd80 () - app task state: speech-detected => processing
**CUDA error 209 at /run/build/whispercpp-cublas/ggml-cuda.cu:6102: no kernel image is available for execution on the device**
[W] 14:13:46.168 0x7f5d825ff600 () - QObject::killTimer: Timers cannot be stopped from another thread
[W] 14:13:46.169 0x7f5d825ff600 () - QObject::~QObject: Timers cannot be stopped from another thread
[D] 14:13:46.178 0x7f5d825ff600 () - speech service dtor
[W] 14:13:46.179 0x7f5d825ff600 () - QtDBus: cannot relay signals from parent speech_service(0x5647aeab6ea0 "") unless they are emitted in the object's thread QThread(0x5647af143ed0 ""). Current thread is QThread(0x7f5d5c0016e0 "").
[D] 14:13:46.179 0x7f5d825ff600 () - mic source dtor
[W] 14:13:46.179 0x7f5d825ff600 () - QObject::killTimer: Timers cannot be stopped from another thread

**Comment by mkiol** [comment]
Thank you for the report.

The problem occurs because binary was not compiled with support for this specific GPU architecture. Your GPU is based on Maxwell (5.0) but supported are [6.0-9.0](https://github.com/mkiol/dsnote/blob/63abbf4caea02ca5b3328ca5495c5f4bd53845e0/flatpak/net.mkiol.SpeechNote.yaml#L879). 

Actually 5.0 is supported on CUDA 12.0, but for unknown reason I didn't enable it - sorry. I will fix it in the next release.

**Comment by mkiol** [comment]
If your video card supports OpenCL, you might try to manually switch to OpenCL (`Settings`->`GPU device`). Acceleration is ~15-20% slower than CUDA but it is still much faster than CPU.

**Comment by mkiol** [comment]
fix: 57c9e6fd66521b7c1d45c5b959d4da37f389a7d6

If you would like, you can test it on the version available on flatpak-beta.

If you're not familiar with flatpak-beta, [here is a short how-to](https://discourse.flathub.org/t/how-to-use-flathub-beta/2111).

**Comment by mkiol** [comment]
This issue is fixed on "beta" release.

You can install and test "beta" version from [`flathub-beta`](https://discourse.flathub.org/t/how-to-use-flathub-beta/2111) channel.
